# Generated by Django 2.0.7 on 2018-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printorder', '0002_auto_20181009_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignname',
            name='name_of_new_camp',
            field=models.CharField(error_messages={'required': 'Кампанія з таким іменем вже існує'}, max_length=50, unique=True),
        ),
    ]
