# Generated by Django 2.0.7 on 2018-10-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printorder', '0003_auto_20181009_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignname',
            name='name_of_new_camp',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=50, unique=True),
        ),
    ]
