# Generated by Django 2.1.3 on 2018-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printorder', '0004_auto_20181009_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignname',
            name='name_of_new_camp',
            field=models.CharField(error_messages={'unique': 'Сюжет з таким іменем вже існує в системі!'}, max_length=50, unique=True),
        ),
    ]
