# Generated by Django 2.1.3 on 2019-03-11 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printorder', '0005_auto_20181105_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_number', models.IntegerField(default=None, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tmp_created_by', to=settings.AUTH_USER_MODEL)),
                ('print_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printorder_comments', to='printorder.PrintOrder')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tmp_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Етап виконання',
                'verbose_name_plural': 'Етапи виконання',
            },
        ),
    ]
