# Generated by Django 2.0.7 on 2018-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_material_in', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('total_material_out_per_month', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('reminder', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
            },
        ),
    ]
