# Generated by Django 2.0.7 on 2018-08-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printstatistics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialCount',
        ),
    ]
