# Generated by Django 2.0.7 on 2018-07-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_material', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
                'ordering': ['name_of_material'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=30)),
                ('material_width', models.FloatField(blank=True, default=None, null=True)),
                ('material_height', models.FloatField(blank=True, default=None, null=True)),
                ('number_of_material', models.IntegerField(blank=True, default=None, null=True)),
                ('m_kv_of_material', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_of_material', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('litr_of_paint', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('number_of_litres', models.IntegerField(blank=True, default=None, null=True)),
                ('all_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_of_paint', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('packing_of_other', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('number_of_other', models.IntegerField(blank=True, default=None, null=True)),
                ('all_of_other', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_of_other', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('paid', models.NullBooleanField(choices=[(None, 'Ні'), (True, 'Так')])),
                ('created', models.DateField(auto_now_add=True, verbose_name='Запис створено')),
                ('updated', models.DateField(auto_now=True, verbose_name='Запис оновлено')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materialorder.MaterialIn')),
            ],
            options={
                'verbose_name': 'Замовлення матеріалу, чорнила, іншого',
                'verbose_name_plural': 'Замовлення матеріалів, чорнил, іншого',
            },
        ),
        migrations.CreateModel(
            name='OtherIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_other', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Інше',
                'verbose_name_plural': 'Все інше',
                'ordering': ['name_of_other'],
            },
        ),
        migrations.CreateModel(
            name='PaintIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_paint', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Чорнило',
                'verbose_name_plural': 'Чорнила',
                'ordering': ['name_of_paint'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_provider', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ['name_of_provider'],
            },
        ),
        migrations.AddField(
            model_name='materialorder',
            name='other',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materialorder.OtherIn'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='paint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materialorder.PaintIn'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materialorder.Provider'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='updated_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
