# Generated by Django 2.0.7 on 2018-07-23 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materialorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='updated_by_user',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
