# Generated by Django 2.0.7 on 2018-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialorder', '0002_auto_20180723_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='all_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Всього літрів'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='all_of_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Всього'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Запис створено'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='invoice',
            field=models.CharField(max_length=30, verbose_name='№ рахунку'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='litr_of_paint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Літри'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='m_kv_of_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='м.кв.'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='material_height',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Довжина'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='material_width',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='number_of_litres',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='К-ть літрів'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='number_of_material',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='number_of_other',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='К-ть'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='packing_of_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='paid',
            field=models.NullBooleanField(choices=[(None, 'Неоплачено'), (True, 'Оплачено')]),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_paint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Запис оновлено'),
        ),
    ]
