# Generated by Django 2.0.7 on 2018-08-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materialorder', '0004_materialorder_total_material_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='total_material_in',
        ),
    ]
