# Generated by Django 2.1.3 on 2018-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialorder', '0005_remove_materialorder_total_material_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='total_of_material_pdv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума з ПДВ'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='total_of_other_pdv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума з ПДВ'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='total_of_paint_pdv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума з ПДВ'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума без ПДВ'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума без ПДВ'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='total_of_paint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сума без ПДВ'),
        ),
    ]
